In [2]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

In [3]:
file_path = r"D:\AssetIQ\data\raw\cmapss\train_FD001.txt"

df = pd.read_csv(file_path, sep=r"\s+", header=None)

df.head()

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,21.61,554.36,2388.06,9046.19,1.3,47.47,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,21.61,553.75,2388.04,9044.07,1.3,47.49,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,21.61,554.26,2388.08,9052.94,1.3,47.27,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,21.61,554.45,2388.11,9049.48,1.3,47.13,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,21.61,554.00,2388.06,9055.15,1.3,47.28,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [4]:
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

Rows: 20631
Columns: 26

In [5]:
columns = (
    ["unit", "cycle", "setting_1", "setting_2", "setting_3"]
    + [f"sensor_{i}" for i in range(1, 22)]
)

df.columns = columns

df.head()

,unit,cycle,setting_1,setting_2,setting_3,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,sensor_9,sensor_10,sensor_11,sensor_12,sensor_13,sensor_14,sensor_15,sensor_16,sensor_17,sensor_18,sensor_19,sensor_20,sensor_21
0,1,1,-0.0007,-0.0004,100.0,518.67,641.82,1589.70,1400.60,14.62,21.61,554.36,2388.06,9046.19,1.3,47.47,521.66,2388.02,8138.62,8.4195,0.03,392,2388,100.0,39.06,23.4190
1,1,2,0.0019,-0.0003,100.0,518.67,642.15,1591.82,1403.14,14.62,21.61,553.75,2388.04,9044.07,1.3,47.49,522.28,2388.07,8131.49,8.4318,0.03,392,2388,100.0,39.00,23.4236
2,1,3,-0.0043,0.0003,100.0,518.67,642.35,1587.99,1404.20,14.62,21.61,554.26,2388.08,9052.94,1.3,47.27,522.42,2388.03,8133.23,8.4178,0.03,390,2388,100.0,38.95,23.3442
3,1,4,0.0007,0.0000,100.0,518.67,642.35,1582.79,1401.87,14.62,21.61,554.45,2388.11,9049.48,1.3,47.13,522.86,2388.08,8133.83,8.3682,0.03,392,2388,100.0,38.88,23.3739
4,1,5,-0.0019,-0.0002,100.0,518.67,642.37,1582.85,1406.22,14.62,21.61,554.00,2388.06,9055.15,1.3,47.28,522.19,2388.04,8133.80,8.4294,0.03,393,2388,100.0,38.90,23.4044

In [6]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 20631 entries, 0 to 20630
Data columns (total 26 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   unit       20631 non-null  int64
 1   cycle      20631 non-null  int64
 2   setting_1  20631 non-null  float64
 3   setting_2  20631 non-null  float64
 4   setting_3  20631 non-null  float64
 5   sensor_1   20631 non-null  float64
 6   sensor_2   20631 non-null  float64
 7   sensor_3   20631 non-null  float64
 8   sensor_4   20631 non-null  float64
 9   sensor_5   20631 non-null  float64
 10  sensor_6   20631 non-null  float64
 11  sensor_7   20631 non-null  float64
 12  sensor_8   20631 non-null  float64
 13  sensor_9   20631 non-null  float64
 14  sensor_10  20631 non-null  float64
 15  sensor_11  20631 non-null  float64
 16  sensor_12  20631 non-null  float64
 17  sensor_13  20631 non-null  float64
 18  sensor_14  20631 non-null  float64
 19  sensor_15  20631 non-null  float64
 20  sensor_16  20631 non-null  float64
 21  sensor_17  20631 non-null  int64
 22  sensor_18  20631 non-null  int64
 23  sensor_19  20631 non-null  float64
 24  sensor_20  20631 non-null  float64
 25  sensor_21  20631 non-null  float64
dtypes: float64(22), int64(4)
memory usage: 4.1 MB

In [7]:
sensor_cols = [f"sensor_{i}" for i in range(1, 22)]

df[sensor_cols].nunique().sort_values()

sensor_1        1
sensor_5        1
sensor_16       1
sensor_10       1
sensor_19       1
sensor_18       1
sensor_6        2
sensor_17      13
sensor_8       53
sensor_13      56
sensor_20     120
sensor_11     159
sensor_2      310
sensor_12     427
sensor_7      513
sensor_15    1918
sensor_3     3012
sensor_4     4051
sensor_21    4745
sensor_14    6078
sensor_9     6403
dtype: int64

In [8]:
constant_sensors = [col for col in sensor_cols if df[col].nunique() == 1]

df[constant_sensors].iloc[0]

sensor_1      518.67
sensor_5       14.62
sensor_10       1.30
sensor_16       0.03
sensor_18    2388.00
sensor_19     100.00
Name: 0, dtype: float64

In [9]:
constant_sensors = [col for col in sensor_cols if df[col].nunique() == 1]

df_model = df.drop(columns=constant_sensors).copy()

print("Removed:", constant_sensors)
print("Original columns:", df.shape[1])
print("Remaining columns:", df_model.shape[1])

Removed: ['sensor_1', 'sensor_5', 'sensor_10', 'sensor_16', 'sensor_18', 'sensor_19']
Original columns: 26
Remaining columns: 20

In [10]:
engine_life = df.groupby("unit")["cycle"].max()

print("Number of engines:", engine_life.shape[0])
print("Minimum lifetime:", engine_life.min())
print("Maximum lifetime:", engine_life.max())
print("Average lifetime:", engine_life.mean())

Number of engines: 100
Minimum lifetime: 128
Maximum lifetime: 362
Average lifetime: 206.31

In [11]:
engine_life.describe()

count    100.000000
mean     206.310000
std       46.342749
min      128.000000
25%      177.000000
50%      199.000000
75%      229.250000
max      362.000000
Name: cycle, dtype: float64

In [12]:
import matplotlib.pyplot as plt

plt.figure(figsize=(10, 5))
plt.bar(engine_life.index, engine_life.values)
plt.xlabel("Engine Unit")
plt.ylabel("Total Operating Cycles")
plt.title("FD001 Engine Lifetimes")
plt.show()

ImportError: DLL load failed while importing _backend_agg: An Application Control policy has blocked this file.

In [1]:
import matplotlib.pyplot as plt
print("Matplotlib ready")

Matplotlib ready

In [3]:
import matplotlib.pyplot as plt

# Engine lifetime visualization
plt.figure(figsize=(10, 5))
plt.bar(engine_life.index, engine_life.values)
plt.xlabel("Engine Unit")
plt.ylabel("Total Operating Cycles")
plt.title("FD001 Engine Lifetimes")
plt.show()

# Shortest and longest-lived engines
print("Shortest-lived engines:")
print(engine_life.sort_values().head(10))

print("\nLongest-lived engines:")
print(engine_life.sort_values(ascending=False).head(10))

ImportError: DLL load failed while importing _backend_agg: An Application Control policy has blocked this file.